import { useState } from "react";
import {
  FileText,
  Copy,
  Check,
  Download,
  Target,
  CheckCircle2,
  ListTodo,
} from "lucide-react";
import type { FinalSummaryData } from "../hooks/useMeetingAI";

interface Props {
  summary: FinalSummaryData;
}

function toMarkdown(summary: FinalSummaryData): string {
  let md = "# Meeting Summary\n\n";
  md += "## Executive Summary\n\n";
  md += summary.executive + "\n\n";

  if (summary.decisions.length > 0) {
    md += "## Key Decisions\n\n";
    summary.decisions.forEach((d) => {
      md += `- ${d}\n`;
    });
    md += "\n";
  }

  if (summary.actionItems.length > 0) {
    md += "## Action Items\n\n";
    summary.actionItems.forEach((a) => {
      md += `- [ ] ${a}\n`;
    });
    md += "\n";
  }

  md += `---\n_Generated by Zerops Meet on ${new Date().toLocaleDateString()}_\n`;
  return md;
}

export default function FinalSummary({ summary }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(toMarkdown(summary));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const md = toMarkdown(summary);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `meeting-summary-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card overflow-hidden">
      {/* Header */}
      <div className="px-4 py-3 border-b border-slate-800/50 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-accent-500" />
          <h3 className="text-sm font-medium text-slate-300">
            Meeting Summary
          </h3>
        </div>
        <div className="flex items-center gap-1">
          <button onClick={handleCopy} className="btn-ghost !px-2 !py-1.5">
            {copied ? (
              <Check className="w-4 h-4 text-accent-400" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </button>
          <button onClick={handleDownload} className="btn-ghost !px-2 !py-1.5">
            <Download className="w-4 h-4" />
          </button>
        </div>
      </div>

      <div className="p-4 space-y-5">
        {/* Executive Summary */}
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Target className="w-4 h-4 text-accent-500" />
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Executive Summary
            </h4>
          </div>
          <p className="text-sm text-slate-300 leading-relaxed">
            {summary.executive}
          </p>
        </div>

        {/* Key Decisions */}
        {summary.decisions.length > 0 && (
          <div>
            <div className="flex items-center gap-2 mb-2">
              <CheckCircle2 className="w-4 h-4 text-blue-400" />
              <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Key Decisions
              </h4>
            </div>
            <ul className="space-y-1.5">
              {summary.decisions.map((d, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-slate-300"
                >
                  <span className="text-blue-400 mt-0.5 flex-shrink-0">→</span>
                  <span>{d}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Action Items */}
        {summary.actionItems.length > 0 && (
          <div>
            <div className="flex items-center gap-2 mb-2">
              <ListTodo className="w-4 h-4 text-amber-400" />
              <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Action Items
              </h4>
            </div>
            <ul className="space-y-1.5">
              {summary.actionItems.map((a, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-slate-300"
                >
                  <span className="w-4 h-4 mt-0.5 flex-shrink-0 rounded border border-slate-600" />
                  <span>{a}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
